### PR TITLE
ED25519 test cases added

### LINKED ISSUE #113: Test of the ED25519 signature implementation
We need to write exhaustive tests to cover ED25519 signature implementation. See https://github.com/near/rainbow-bridge/blob/810267b21d12c21dab75892e76c3a9904861b6cd/libs-sol/nearbridge/test/NearBridge.js#L91 as an example of tests of Solidity contract.

See ED25519 source code here: https://github.com/near/rainbow-bridge/blob/6edbdd2b211d00309e66725f7f6a0b28d689d0ce/libs-sol/nearbridge/contracts/Ed25519.sol#L4

### PR DESCRIPTION
**Pull request by fckt**
fixes #113 
Question: how to add it to the CI pipeline? 

@nearmax @ailisp

### CODE REVIEW

**Comment by nearmax** [comment]
verify eth headers is the only test that's failing. It is failing because it is not implemented yet. I am going to merge this PR now.

**Comment by nearmax** [comment]
@ailisp I am not sure this test is connected to the CI. Could you please connect it?

**Comment by ailisp** [comment]
@nearmax added

**Comment by nearmax** [comment]
> @nearmax added

Thank you

**Comment by fckt** [comment]
@ailisp btw, why the CI configuration is not in a file inside of the repository? To me having CI configuration in repository is something taken for granted..

**Comment by ailisp** [comment]
> @ailisp btw, why the CI configuration is not in a file inside of the repository? To me having CI configuration in repository is something taken for granted..

It can be if we want. CI not in repo was inherited from what nearcore did, because we want single place to control different branches, place ci file in repo proved to be problematic when we use gitlab ci. For bridge it makes sense to have it in repo

**Pull request merged**
