### PR TITLE
fix NearProver

### PR DESCRIPTION
**Pull request by bowenwang1996**
The prover was incorrect because it computes the shard outcome root and tries to assert that it is the same as the block outcome root.

### CODE REVIEW

**Comment by ailisp** [comment]
running near prover test on your branch to see if ci configuration is good https://buildkite.com/nearprotocol/rainbow-bridge/builds/3

**Comment by ailisp** [comment]
@nearmax eth-prover test is fixed in this PR, https://buildkite.com/nearprotocol/rainbow-bridge/builds/6#1c4e8961-9cbd-46dc-a113-916cb7d44e87
I think this can be merged?

**Comment by ailisp** [comment]
@bowenwang1996 looks it's still failing: https://buildkite.com/nearprotocol/rainbow-bridge/builds/28#bf2d83e9-126f-44cd-b76a-3e9efc1f79f4 (ignore all other tests, cancelled intentionally)

**Comment by nearmax** [comment]
@ailisp  I am reading this code currently, will investigate.

**Comment by bowenwang1996** [comment]
I believe @k06a didn't push the latest code.

**Comment by ailisp** [comment]
updated branch to avoid ci stuck

**Pull request merged**
