### PR TITLE
index.js status

### PR DESCRIPTION
**Pull request by Kouprin**
First version of `node index.js status` command. Related to #257.

Answer for turned ganache/near-node on:
Screen Shot 2020-08-09 at 2 58 46 PM

Answer for turned ganache/near-node off:
Screen Shot 2020-08-09 at 2 59 20 PM

Known issues:
1. Not checking bytecode of deployed ETH contracts. Not sure is it possible. Marked as TODO.
2. Not checking NEAR Contracts validity because of poor and unclear access to them. Marked as TODO.
3. No eth-relay/near-relay/watchdog status.

@nearmax, @ailisp if you can help with 1 or 2 please do.

### CODE REVIEW

**Comment by Kouprin** [comment]
> Looks good so fat, would be helpful to also add near-relay/eth-relay/watchdog status from pm2

Absolutely. There is an issue https://github.com/near/rainbow-bridge/issues/257.

**Comment by ailisp** [comment]
> Not checking NEAR Contracts validity because of poor and unclear access to them. Marked as TODO.

For near contract, they have initialized() method: https://github.com/near/rainbow-bridge/blob/master/libs-rs/eth-client/src/lib.rs#L151 try to call that method, and if contract is not present or not intialized, you'll get error.

> Not checking bytecode of deployed ETH contracts. Not sure is it possible. Marked as TODO.

Seems possible with this method:
https://web3js.readthedocs.io/en/v1.2.9/web3-eth.html#getcode

**Comment by Kouprin** [comment]
> > Not checking NEAR Contracts validity because of poor and unclear access to them. Marked as TODO.
> 
> For near contract, they have initialized() method: https://github.com/near/rainbow-bridge/blob/master/libs-rs/eth-client/src/lib.rs#L151 try to call that method, and if contract is not present or not intialized, you'll get error.
> 
> > Not checking bytecode of deployed ETH contracts. Not sure is it possible. Marked as TODO.
> 
> Seems possible with this method:
> https://web3js.readthedocs.io/en/v1.2.9/web3-eth.html#getcode

Both solutions don't work for me.

First one is implemented specifically for Eth2NearClientContract. I don't know how to get access to it and do something like:
```
const contract = new nearlib.Contract(masterAccount, contractAccount, {});
const initialized = await contract.initialized();
```
As expected, I get an error:
```
TypeError: contract.initialized is not a function
```

The second one I use the following way:
```
console.log(await web3.eth.getCode(address));
```
and it always returns `0x0`.

**Comment by Kouprin** [comment]
I'm merging this one and we'll figure out how to resolve minor issues later.

**Comment by ailisp** [comment]
> const contract = new nearlib.Contract(masterAccount, contractAccount, {});
const initialized = await contract.initialized();

You need to list all method that contract have (or at least `init method`), example: https://github.com/near/rainbow-bridge/blob/master/environment/commands/init-near-fun-token.js#L39


> console.log(await web3.eth.getCode(address));

This sucks, seem i can get a lot of "web3 getCode get 0x0" search result but couldn't see a solution. Have you try ganache gui https://www.trufflesuite.com/ganache? They have a contract view, we may find out how they get the info from there source.

**Pull request merged**
